### ISSUE TITLE
Master checklist

### ISSUE THREAD

**Issue by leeyap** [BennettForville/Bshiny2#3]
Here are the remaining tasks for Bennett's Shiny app:
(@BennettForville and @bpbond please edit and add to this list as you see fit!)

- [x] Write content for the homepage (draft for Wednesday 4/13 // draft 2 for Wednesday 4/20)
- [x] Write content for the impacts section, citing readings (linking to the output parameters) (draft for Friday 4/15 // draft 2 for Wednesday 4/20)
- [x] Finalize choices and define input and output parameters (4/20)
- [x] Write code for SSP hover bars
- [x] Tweak graphs to show different units (@leeyap will help with code for 4/11) and visually (maybe)

Low priority:
- [x] actionButton for next page (🙃) - Bennett to email Steph P
- [ ] Add pictures

**Comment by bpbond** [comment]
- [ ] Change graph facet labels to be more self-explanatory

```r
> x <- data.frame(unclear_name = c("A", "B"), stringsAsFactors = FALSE)
> labels <-  c("A" = "Apple", "B" = "Bear")
> x$clearer_name <- labels[x$unclear_name]
> x
  unclear_name clearer_name
1            A        Apple
2            B         Bear
```

**Comment by leeyap** [comment]
Adding in some timeline dates from the Google Sheet schedule:

Apr 28: Presentation skills workshop
May 5: Submit abstract to IR
May 9: Symposium practice
May 12: submit ppt to IR
May 12: submit abstract to OSE for brochure
May 19: Symposium!!
May 20: Exit interviews
